spring:
  # ----------------------------mysql-------------------------- #
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      # useSSL:高版本的MySQL是否进行ssl链接
#      url: jdbc:mysql://10.10.10.10:3306/myDB?characterEncoding=utf8&useSSL=false
#      username: linb
#      password: imissyou
      url: jdbc:mysql://120.78.107.157:3306/app?characterEncoding=utf8&useSSL=false
      username: root
      password: 1+1=zyes

  # ----------------------------mongo-------------------------- #
#  data:
#    mongodb:
#      uri: mongodb://feature_peoplexs_test:Feature1234@172.30.10.31:40012/feature_peoplexs_test
  # -----------------------------jpa--------------------------- #
#  jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: none
#        naming:
#          # 表命名规格定义
#          physical-strategy: org.clc.common.mysql.MySQLUpperCaseStrategy

  # ----------------------------jackson------------------------- #
  jackson:
      # 日期json输出格式
      date-format: yyyy-MM-dd HH:mm:ss
      # 时区
      time-zone: GMT+8

  # --------------------------thymeleaf------------------------ #
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
# ----------------------------mybatis-------------------------- #
mybatis:
  # 加载mapper配置文件
  mapper-locations: classpath:mapper/*-mapper.xml
  config-location: classpath:mapper/config/mybatis-config.xml
#  configuration:
#    interceptors:
#      - org.clc.common.mybatisPlugin.MybatisInterceptor
logging:
  level:
    org.clc.kernel.mysql.mapper: debug
    org.clc.config: debug
  # ------------------REDIS (RedisProperties)------------------ #
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    host: 10.10.10.10
#    port: 6379
#    password: imissyou #（默认为空）
#    # 连接超时时间（毫秒）
#    timeout: 0
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0
