server:
  port: 8888
  #https 配置
  ssl:
    key-store: https.key
    key-store-type: JKS
    key-password: imissyou
    key-alias: https
    key-store-password: imissyou
spring:
  profiles:
    active: dev